"""HTML reporter — generates a standalone HTML report."""

from __future__ import annotations

from datetime import datetime, timezone

from openseo_lens import __version__
from openseo_lens.models import AnalysisResult, Severity
from openseo_lens.reporters import ReporterBase


class HtmlReporter(ReporterBase):
    """Render analysis results as a standalone HTML page."""

    def render(self, result: AnalysisResult) -> str:
        """Render the analysis result as an HTML string."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        scores_html = ""
        for score in result.scores:
            label = score.category.value.replace("_", " ").title()
            pct = score.percentage
            scores_html += f"""
            <div class="score-card">
                <h3>{label}</h3>
                <div class="score-bar">
                    <div class="score-fill" style="width: {pct}%"></div>
                </div>
                <span class="score-value">{score.value}/{score.max_value}</span>
            </div>"""

        severity_colors = {
            Severity.HIGH: "#e74c3c",
            Severity.MEDIUM: "#f39c12",
            Severity.LOW: "#3498db",
            Severity.INFO: "#95a5a6",
        }

        issues_html = ""
        for issue in result.issues:
            color = severity_colors[issue.severity]
            issues_html += f"""
            <div class="issue">
                <span class="severity" style="background: {color}">
                    {issue.severity.value.upper()}
                </span>
                <strong>{issue.title}</strong>
                <p>{issue.description}</p>
                <p class="recommendation">{issue.recommendation}</p>
            </div>"""

        if not result.issues:
            issues_html = '<p class="no-issues">No issues found.</p>'

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OpenSEO Lens Report — {result.url}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: system-ui, sans-serif; background: #0d1117; color: #c9d1d9; padding: 2rem; }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        h1 {{ color: #58a6ff; margin-bottom: 0.5rem; }}
        h2 {{ color: #c9d1d9; margin: 2rem 0 1rem; border-bottom: 1px solid #21262d; padding-bottom: 0.5rem; }}
        .url {{ color: #8b949e; margin-bottom: 2rem; }}
        .overall {{ font-size: 3rem; font-weight: bold; color: #3fb950; text-align: center; margin: 2rem 0; }}
        .scores {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }}
        .score-card {{ background: #161b22; border: 1px solid #21262d; border-radius: 8px; padding: 1rem; }}
        .score-card h3 {{ font-size: 0.9rem; color: #8b949e; margin-bottom: 0.5rem; }}
        .score-bar {{ background: #21262d; border-radius: 4px; height: 8px; margin-bottom: 0.5rem; }}
        .score-fill {{ background: #3fb950; height: 100%; border-radius: 4px; }}
        .score-value {{ font-weight: bold; }}
        .issue {{ background: #161b22; border: 1px solid #21262d; border-radius: 8px; padding: 1rem; margin-bottom: 0.5rem; }}
        .severity {{ color: #fff; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: bold; margin-right: 0.5rem; }}
        .recommendation {{ color: #8b949e; font-style: italic; margin-top: 0.5rem; }}
        .no-issues {{ color: #3fb950; }}
        footer {{ margin-top: 3rem; color: #484f58; text-align: center; font-size: 0.85rem; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>OpenSEO Lens</h1>
        <p class="url">AI Search Readiness Report for <strong>{result.url}</strong></p>

        <div class="overall">{result.overall_score}/100</div>

        <h2>Scores by Dimension</h2>
        <div class="scores">{scores_html}</div>

        <h2>Issues ({result.issue_count})</h2>
        {issues_html}

        <footer>
            Generated by OpenSEO Lens v{__version__} on {now}
        </footer>
    </div>
</body>
</html>"""
